export const UserDTOKeys = [
  'id',
  'email',
  'phone',
  'adminType',
  'emailVerified',
  'phoneVerified',
  'registeredVia',
  'isBlocked',
  'name',
  'isActive',
  'isAdmin',
  'sessionId',
  'whatsappId',
  'customProps',
  'updated_at',
  'isAdminFor',
]

export const UserForAdminDTOKeys = [
  'id',
  'email',
  'phone',
  'adminType',
  'emailVerified',
  'phoneVerified',
  'registeredVia',
  'isBlocked',
  'name',
  'isActive',
  'isAdmin',
  'whatsappId',
  'customProps',
]
