export const UserDTOKeys = [
  "email",
  "phone",
  "adminType",
  "emailVerified",
  "phoneVerified",
  "registeredVia",
  "isBlocked",
  "name",
  "isActive",
  "isAdmin",
  "sessionId",
  "whatsappId",
  "customProps",
]

export const UserForAdminDTOKeys = [
  "email",
  "phone",
  "adminType",
  "emailVerified",
  "phoneVerified",
  "registeredVia",
  "isBlocked",
  "name",
  "isActive",
  "isAdmin",
  "whatsappId",
  "customProps",
]
